#!/bin/bash
set -e -v

### PICK VERSION
export JAVA_HOME=/usr/lib/jvm/java-7-oracle
export PATH=$JAVA_HOME/bin:$PATH

### CHECK VERSION
java -version

### COMPILE
cat $1 >Unsound.java
javac Unsound.java

### RUN
java Unsound
